import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import 'react-loading-skeleton/dist/skeleton.css'
import { Suspense } from "react";
import Loading from "./loading";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-white`}>
        <Suspense fallback={<Loading />}>
        <StoreProvider>{children}</StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
